// Copyright (C) 1991-2015 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus II License Agreement,
// the Altera MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Altera and sold by Altera or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus II 64-Bit Version 15.0 (Build Build 145 04/22/2015)
// Created on Fri Jan 15 09:59:08 2021

My_Distance_Count My_Distance_Count_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.RTSn(RTSn_sig) ,	// input  RTSn_sig
	.test_count(test_count_sig) ,	// input  test_count_sig
	.Hundred(Hundred_sig) ,	// output [3:0] Hundred_sig
	.Ten(Ten_sig) ,	// output [3:0] Ten_sig
	.One(One_sig) ,	// output [3:0] One_sig
	.D_Ten(D_Ten_sig) ,	// output [3:0] D_Ten_sig
	.D_Hundred(D_Hundred_sig) ,	// output [3:0] D_Hundred_sig
	.LED_Out(LED_Out_sig) 	// output [7:0] LED_Out_sig
);

defparam My_Distance_Count_inst.eee = 'b000000000011001110110011;
defparam My_Distance_Count_inst.led_30 = 'b000000010101100010101011;
defparam My_Distance_Count_inst.H = 'b000001000111110011100110;
defparam My_Distance_Count_inst.T = 'b000000000111001011100100;
defparam My_Distance_Count_inst.O = 'b000000000000101101111101;
defparam My_Distance_Count_inst.DT = 'b000000000000000100100110;
defparam My_Distance_Count_inst.DH = 'b000000000000000000011101;
defparam My_Distance_Count_inst.T5HZ = 'b010011000100101100111111;
