// Copyright (C) 1991-2015 Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus II License Agreement,
// the Altera MegaCore Function License Agreement, or other 
// applicable license agreement, including, without limitation, 
// that your use is for the sole purpose of programming logic 
// devices manufactured by Altera and sold by Altera or its 
// authorized distributors.  Please refer to the applicable 
// agreement for further details.


// Generated by Quartus II 64-Bit Version 15.0 (Build Build 145 04/22/2015)
// Created on Thu Jan 14 18:56:21 2021

My_Dig My_Dig_inst
(
	.CLK(CLK_sig) ,	// input  CLK_sig
	.Hundred(Hundred_sig) ,	// input [3:0] Hundred_sig
	.Ten(Ten_sig) ,	// input [3:0] Ten_sig
	.One(One_sig) ,	// input [3:0] One_sig
	.D_Ten(D_Ten_sig) ,	// input [3:0] D_Ten_sig
	.D_Hundred(D_Hundred_sig) ,	// input [3:0] D_Hundred_sig
	.Digitron_Out(Digitron_Out_sig) ,	// output [7:0] Digitron_Out_sig
	.DigitronCS_Out(DigitronCS_Out_sig) 	// output [5:0] DigitronCS_Out_sig
);

defparam My_Dig_inst.T250K = 'b0000000011001000;
defparam My_Dig_inst._0 = 'b00111111;
defparam My_Dig_inst._1 = 'b00000110;
defparam My_Dig_inst._2 = 'b01011011;
defparam My_Dig_inst._3 = 'b01001111;
defparam My_Dig_inst._4 = 'b01100110;
defparam My_Dig_inst._5 = 'b01101101;
defparam My_Dig_inst._6 = 'b01111101;
defparam My_Dig_inst._7 = 'b00000111;
defparam My_Dig_inst._8 = 'b01111111;
defparam My_Dig_inst._9 = 'b01101111;
